:doctype: book

:stylesdir: ../stylesheets/
:stylesheet: etf.css
:linkcss:

:toc: macro
:toc-title: Table of contents
:toclevels: 2
:toc-position: left
:appendix-caption: Annex

:icons: font
:docinfo: shared

:source-highlighter: pygments
:pygments-style: autumn
:pygments-linenums-mode: inline

include::../General/Logo.adoc[]

:doc-warning-work-in-progress: false
:doc-title: Building ETF
:doc-status: approved
:doc-date: 2022-08-17
:doc-description: This manual describes how to build the ETF validator. Knowledge about maven, maven repositories and build management tools are required.
:doc-audience: Developers planning to build the ETF validator themselves
:doc-id: https://docs.etf-validator.net/v2.0/Developer_manuals/Building.html
:doc-lang: EN

include::../General/Document-metadata.adoc[]

== Changelog
[width="100%",options="header",cols="1,2,3"]
|===
|  *Date* | *Editor* | *Comments*
| 2017-05-02 | Jon Herrmann | document created
| 2017-06-21 | Clemens Portele | editorial updates
| 2017-07-12 | Jon Herrmann | Test driver development section
| 2022-08-17 | Guadaltel | Updated to v2.1
| 2022-08-24 | Jon Herrmann  | some changes, approved
|===

<<<

toc::[]

<<<

include::../General/About-short.adoc[]

== Prerequisites

- link:https://jdk.java.net/archive/[OpenJDK 11 is installed]
- Ensure JAVA_HOME environment variable is set
- link:https://git-scm.com/downloads[Git installed]
- For debugging: an IDE with the corresponding plugins 
for an web application server (for instance link:https://plugins.jetbrains.com/plugin/18721-jetty[this IntelliJ plugin] or link:https://marketplace.eclipse.org/content/eclipse-jetty[this plugin for Eclipse]). Or you install an web application server and connect via an open debug port.

== Cloning the source code

Clone the Source code from the link:https://github.com/etf-validator/etf-webapp[GitHub repository].

[source,bash]
----
git clone -b next https://github.com/etf-validator/etf-webapp.git
----

NOTE: the next branch contains the latests developments.

== Compiling the source code

ETF uses link:https://gradle.org[Gradle] as build management tool. The gradle
wrapper script will automatically download the required Gradle version and
start the build process afterwards.

Dependencies are currently downloaded from the interactive instruments repositories.
Currently only the snapshot repository can be accessed with the credentials
etf-public-dev / etf-public-dev . This is automatically done by
default.

[NOTE]
====
The artifact repository to be used is determined from the version.properties file.
Make sure the version is suffixed with "-SNAPSHOT". If necessary, change the
version in the version.properties file, for example to:

----
version = 2.1.0-SNAPSHOT
----
====


.On a Windows command line run
[source,cmd]
----
C:\etf-webapp> gradlew.bat build war
----

.On Linux execute
[source,bash]
----
$ ./gradlew build war
----


== Using test drivers with the web application

Each Test Driver can be installed in the link:Admin_manuals/index.html#_etf_data_directory_structure[test driver directory] and will be used by ETF on startup.

To build the test drivers the following repositories need to be cloned:

- link:https://github.com/etf-validator/etf-bsxtd.git[etf-bsxtd] ETF test driver for running BaseX XQuery based test projects
- link:https://github.com/etf-validator/etf-tetd.git[etf-tetd] ETF test driver for executing Test Suites on a remote OGC TEAM Engine instance
- link:https://github.com/etf-validator/etf-suitd.git[etf-suitd] ETF test driver for running SoapUI based test projects

Test drivers then should be built with the following commands (replace the TMP with you test driver directory):

.On a Windows command line run
[source,cmd]
----
C:\etf-testdriver> gradlew.bat -Petf.td.deployment.dir="C:\TMP" build install
----
.On Linux execute
[source,bash]
----
$ gradlew.bat -Petf.td.deployment.dir="/TMP" build install
----

NOTE: If your git client changes the line endings, your need to add the 
"spotlessApply" task to the build commands.

== FAQ
Q: I get a `repository not found` error.

A: The error occurs for example if the source code has been downloaded and not
cloned with GIT -or the directory has been copied without the hidden .git
directory. The build helper script (etf-bda) collects information from the
locally cloned GIT repository and includes the property `Implementation-Revision`
in the manifest file:
----
Manifest-Version: 1.0
Build-Date: 170601013212
Implementation-Version: 2.0.0
Build-Gradle: 3.5
Build-ii-bda: 1.0.24.1
Implementation-Revision: abf509f
Source-Compatibility: 1.8
Implementation-Build: 0
Build-Host: JAX
Build-User: herrmann
Build-JDK: 1.8.0_102
----
You can fix the problem by cloning the repository from GitHub using GIT.

Q: I obtain different sizes in the war or jar files than the size of the released artifacts
when I compile them in my environment.

A: These differences result from several local system properties that are collected by the build system and included in the manifest file. 


***

include::../General/Legal_Privacy.adoc[]
